# Dependencies
markdown:         kramdown
# redcarpet:        
#   extensions: ["tables"]
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Pedro Matias
description:      ''

# Custom vars
github:           https://github.com/zydeon
linkedin:         https://www.linkedin.com/in/pamatias
email:            contact@pedromatias.me
images:           /assets
css:              /assets/css
project_images:   /assets/projects

# defaults
defaults:
  -
    scope:
      path: "research"
      type: "posts"
    values:
      category: "research"
  -
    scope:
      path: "development"
      type: "posts"
    values:
      category: "development"