# Dependencies
markdown:         kramdown
# kramdown:
  # input: GFM
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Pedro Matias
description:      ''

# Custom vars
github:           https://github.com/zydeon
linkedin:         https://www.linkedin.com/in/pamatias
email:            pedro@pmatias.com
hackerrank:       https://hackerrank.com/zydeon


# defaults
defaults:
  -
    scope:
      path: "research/projects" # an empty string here means all files in the project
    values:
      category: "research"
  -
    scope:
      path: "development/projects" # an empty string here means all files in the project
    values:
      category: "development"