# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Pedro Matias
description:      ''

# Custom vars
github:           https://github.com/zydeon
linkedin:         https://www.linkedin.com/in/pamatias
email:            me@pedromatias.me


# defaults
defaults:
  -
    scope:
      path: "research/projects" # an empty string here means all files in the project
    values:
      category: "research"
  -
    scope:
      path: "development/projects" # an empty string here means all files in the project
    values:
      category: "development"