# Dependencies
markdown:         kramdown
# kramdown:
  # input: GFM
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Pedro Matias
description:      ''

# Plugins
gems:             []

# Custom vars
github:           https://github.com/zydeon
linkedin:         https://www.linkedin.com/in/pamatias
email:            pedro@pmatias.com
hackerrank:       https://hackerrank.com/zydeon

# Navigation
navbar:
  Home:         "/"
  Research:     "/research"
  Development:  "/development"
  Blog:         "http://blog.pmatias.com"


# defaults
defaults:
  -
    scope:
      path: "research/projects" # an empty string here means all files in the project
    values:
      category: "research"
  -
    scope:
      path: "development/projects" # an empty string here means all files in the project
    values:
      category: "development"