# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Pedro Matias
description:      ''
baseurl:          /

paginate:         5

# Custom vars
github:           https://github.com/zydeon
linkedin:         https://www.linkedin.com/in/pamatias
email:            me@pedromatias.me
